# Import Libraries

In [21]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

# Import Datasets

In [30]:
# training data
train_raw_pre = pd.read_csv('Dataset/Pre Processed Data/train_raw_pre.csv')

# testing data
test_raw_pre = pd.read_csv('Dataset/Pre Processed Data/test_raw_pre.csv')

# Principal Component Analysis (PCA)

In [31]:
# view the train data
train_raw_pre.head()

,Unnamed: 0,X10,X11,X12,X13,X14,X15,X16,X17,X18,...,X8_q,X8_r,X8_s,X8_t,X8_u,X8_v,X8_w,X8_x,X8_y,y
0,0,0,0,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,130.81
1,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,88.53
2,2,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,76.26
3,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,80.62
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,78.02

In [32]:
# view the test data
test_raw_pre.head()

,Unnamed: 0,X10,X11,X12,X13,X14,X15,X16,X17,X18,...,X8_p,X8_q,X8_r,X8_s,X8_t,X8_u,X8_v,X8_w,X8_x,X8_y
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,2,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [33]:
# drop the columns 'Unnamed: 0'
train_raw_pre = train_raw_pre.drop(['Unnamed: 0'], axis = 1)
test_raw_pre = test_raw_pre.drop(['Unnamed: 0'], axis = 1)

In [34]:
train_raw_pre.head()

,X10,X11,X12,X13,X14,X15,X16,X17,X18,X19,...,X8_q,X8_r,X8_s,X8_t,X8_u,X8_v,X8_w,X8_x,X8_y,y
0,0,0,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,130.81
1,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,88.53
2,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,76.26
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,80.62
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,78.02

In [ ]:
test_raw_pre.head()

In [35]:
# Loading the PCA object for training set
pca = PCA(n_components = 2) # Here we choose the number of components that we will keep.
pca_train = pca.fit_transform(train_raw_pre)
pca_train_df = pd.DataFrame(pca_train, columns = ['principal_component_1','principal_component_2'])

# Loading the PCA object for test set
pca = PCA(n_components = 2) # Here we choose the number of components that we will keep.
pca_test = pca.fit_transform(test_raw_pre)
pca_test_df = pd.DataFrame(pca_test, columns = ['principal_component_1','principal_component_2'])

In [38]:
# view the train set
pca_train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Data columns (total 2 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   principal_component_1  4209 non-null   float64
 1   principal_component_2  4209 non-null   float64
dtypes: float64(2)
memory usage: 65.9 KB

In [39]:
# view the test set
pca_test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Data columns (total 2 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   principal_component_1  4209 non-null   float64
 1   principal_component_2  4209 non-null   float64
dtypes: float64(2)
memory usage: 65.9 KB

**Export the dataset**

In [41]:
# export training set
pca_train_df.to_csv('Dataset/PCA Data/pca_train.csv')

# export testing set
pca_test_df.to_csv('Dataset/PCA Data/pca_test.csv')