<img src="http://cfs22.simplicdn.net/ice9/new_logo.svgz "/>

# Assignment 01: Evaluate the FAA Dataset

*The comments/sections provided are your cues to perform the assignment. You don't need to limit yourself to the number of rows/cells provided. You can add additional rows in each section to add more lines of code.*

*If at any point in time you need help on solving this assignment, view our demo video to understand the different steps of the code.*

**Happy coding!**

* * *

#### 1: VIew and import the dataset

In [1]:
#Import necessary libraries
import pandas as pd

In [3]:
#Import the FAA (Federal Aviation Authority) dataset
df_faa_dataset = pd.read_csv('/Users/PoroBurman/Desktop/PG_AI/Data_Manipulation_with_Pandas/faa_ai_prelim.csv')

#### 2: View and understand the dataset

In [4]:
#View the dataset shape
df_faa_dataset.shape

(83, 42)

In [5]:
#View the first five observations
df_faa_dataset.head()

,UPDATED,ENTRY_DATE,EVENT_LCL_DATE,EVENT_LCL_TIME,LOC_CITY_NAME,LOC_STATE_NAME,LOC_CNTRY_NAME,RMK_TEXT,EVENT_TYPE_DESC,FSDO_DESC,...,PAX_INJ_NONE,PAX_INJ_MINOR,PAX_INJ_SERIOUS,PAX_INJ_FATAL,PAX_INJ_UNK,GRND_INJ_NONE,GRND_INJ_MINOR,GRND_INJ_SERIOUS,GRND_INJ_FATAL,GRND_INJ_UNK
0,No,19-FEB-16,19-FEB-16,00:45:00Z,MARSHVILLE,North Carolina,NaN,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",Accident,FAA Charlotte FSDO-68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,No,19-FEB-16,18-FEB-16,23:55:00Z,TAVERNIER,Florida,NaN,AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...,Incident,FAA Miami FSDO-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,No,19-FEB-16,18-FEB-16,22:14:00Z,TRENTON,New Jersey,NaN,"AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...",Incident,FAA Philadelphia FSDO-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,No,19-FEB-16,18-FEB-16,17:10:00Z,ASHEVILLE,North Carolina,NaN,"AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...",Incident,FAA Charlotte FSDO-68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,No,19-FEB-16,18-FEB-16,00:26:00Z,TALKEETNA,Alaska,NaN,"AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...",Incident,FAA Anchorage FSDO-03,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
#View all the columns present in the dataset
df_faa_dataset.columns

Index(['UPDATED', 'ENTRY_DATE', 'EVENT_LCL_DATE', 'EVENT_LCL_TIME',
       'LOC_CITY_NAME', 'LOC_STATE_NAME', 'LOC_CNTRY_NAME', 'RMK_TEXT',
       'EVENT_TYPE_DESC', 'FSDO_DESC', 'REGIST_NBR', 'FLT_NBR', 'ACFT_OPRTR',
       'ACFT_MAKE_NAME', 'ACFT_MODEL_NAME', 'ACFT_MISSING_FLAG',
       'ACFT_DMG_DESC', 'FLT_ACTIVITY', 'FLT_PHASE', 'FAR_PART', 'MAX_INJ_LVL',
       'FATAL_FLAG', 'FLT_CRW_INJ_NONE', 'FLT_CRW_INJ_MINOR',
       'FLT_CRW_INJ_SERIOUS', 'FLT_CRW_INJ_FATAL', 'FLT_CRW_INJ_UNK',
       'CBN_CRW_INJ_NONE', 'CBN_CRW_INJ_MINOR', 'CBN_CRW_INJ_SERIOUS',
       'CBN_CRW_INJ_FATAL', 'CBN_CRW_INJ_UNK', 'PAX_INJ_NONE', 'PAX_INJ_MINOR',
       'PAX_INJ_SERIOUS', 'PAX_INJ_FATAL', 'PAX_INJ_UNK', 'GRND_INJ_NONE',
       'GRND_INJ_MINOR', 'GRND_INJ_SERIOUS', 'GRND_INJ_FATAL', 'GRND_INJ_UNK'],
      dtype='object')

#### 3: Extract the following attributes from the dataset:
1. Aircraft make name
2. State name
3. Aircraft model name
4. Text information
5. Flight phase
6. Event description type
7. Fatal flag

In [7]:
#Create a new dataframe with only the required columns
df_analyze_dataset = df_faa_dataset[['ACFT_MAKE_NAME', 'LOC_STATE_NAME', 'ACFT_MODEL_NAME', 'RMK_TEXT',
                                    'FLT_PHASE', 'EVENT_TYPE_DESC', 'FATAL_FLAG']]

In [8]:
#View the type of the object
df_analyze_dataset.shape

(83, 7)

In [9]:
#Check if the dataframe contains all the required attributes
df_analyze_dataset.head()

,ACFT_MAKE_NAME,LOC_STATE_NAME,ACFT_MODEL_NAME,RMK_TEXT,FLT_PHASE,EVENT_TYPE_DESC,FATAL_FLAG
0,BEECH,North Carolina,36,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",UNKNOWN (UNK),Accident,Yes
1,VANS,Florida,RV7,AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...,LANDING (LDG),Incident,NaN
2,CESSNA,New Jersey,172,"AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...",APPROACH (APR),Incident,NaN
3,LANCAIR,North Carolina,235,"AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...",LANDING (LDG),Incident,NaN
4,CESSNA,Alaska,172,"AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...",LANDING (LDG),Incident,NaN

#### 4. Clean the dataset and replace the fatal flag NaN with “No”

In [10]:
#Replace all Fatal Flag missing values with the required output
df_analyze_dataset['FATAL_FLAG'].fillna(value = 'No', inplace=True)

/Users/PoroBurman/opt/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py:6245: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)

In [14]:
#Verify if the missing values are replaced
df_analyze_dataset['FATAL_FLAG'].isnull().sum().sum()

0

In [15]:
#Check the number of observations
df_analyze_dataset['FATAL_FLAG'].head()

0    Yes
1     No
2     No
3     No
4     No
Name: FATAL_FLAG, dtype: object

#### 5. Remove all the observations where aircraft names are not available

In [16]:
#Drop the unwanted values/observations from the dataset
df_analyze_dataset[df_analyze_dataset['ACFT_MAKE_NAME'].notna()]

,ACFT_MAKE_NAME,LOC_STATE_NAME,ACFT_MODEL_NAME,RMK_TEXT,FLT_PHASE,EVENT_TYPE_DESC,FATAL_FLAG
0,BEECH,North Carolina,36,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",UNKNOWN (UNK),Accident,Yes
1,VANS,Florida,RV7,AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...,LANDING (LDG),Incident,No
2,CESSNA,New Jersey,172,"AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...",APPROACH (APR),Incident,No
3,LANCAIR,North Carolina,235,"AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...",LANDING (LDG),Incident,No
4,CESSNA,Alaska,172,"AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...",LANDING (LDG),Incident,No
...,...,...,...,...,...,...,...
78,AERONCA,Texas,O58B,"AIRCRAFT ON LANDING, GROUND LOOPED, BULVERDE A...",LANDING (LDG),Accident,No
79,NORTH AMERICAN,Arizona,F51,"AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES, ...",UNKNOWN (UNK),Accident,Yes
80,CHAMPION,California,8KCAB,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",UNKNOWN (UNK),Accident,Yes
81,BEECH,California,35,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",UNKNOWN (UNK),Accident,Yes
82,CESSNA,Alabama,182,N784CP AIRCRAFT CRASHED INTO A WOODED AREA NEA...,UNKNOWN (UNK),Accident,Yes

#### 6. Find the aircraft types and their occurrences in the dataset

In [21]:
#Check the number of observations now to compare it with the original dataset and see how many values have been dropped
df_analyze_dataset.ACFT_MAKE_NAME.value_counts()

CESSNA                    23
PIPER                     10
BEECH                      9
MOONEY                     4
BOEING                     3
LANCAIR                    2
SOCATA                     2
BELL                       2
CHAMPION                   2
PITTS                      1
CONSOLIDATED VULTEE        1
GRUMMAN                    1
AIRBUS                     1
MAULE                      1
SABRELINER                 1
GLOBE                      1
AERONCA                    1
SAAB                       1
NORTH AMERICAN             1
VANS                       1
HUGHES                     1
CHRISTEN                   1
ENSTROM                    1
GREAT LAKES                1
AERO COMMANDER             1
EMBRAER                    1
FAIRCHILD                  1
FLIGHT DESIGN              1
AEROSTAR INTERNATIONAL     1
GULFSTREAM                 1
Name: ACFT_MAKE_NAME, dtype: int64

In [23]:
#Group the dataset by aircraft name
df_analyze_dataset.groupby('ACFT_MAKE_NAME').head()

,ACFT_MAKE_NAME,LOC_STATE_NAME,ACFT_MODEL_NAME,RMK_TEXT,FLT_PHASE,EVENT_TYPE_DESC,FATAL_FLAG
0,BEECH,North Carolina,36,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",UNKNOWN (UNK),Accident,Yes
1,VANS,Florida,RV7,AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...,LANDING (LDG),Incident,No
2,CESSNA,New Jersey,172,"AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...",APPROACH (APR),Incident,No
3,LANCAIR,North Carolina,235,"AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...",LANDING (LDG),Incident,No
4,CESSNA,Alaska,172,"AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...",LANDING (LDG),Incident,No
5,BELL,Hawaii,206,N80918 BELL 206B ROTORCRAFT CRASHED INTO THE W...,UNKNOWN (UNK),Accident,No
6,PIPER,Florida,PA24,"AIRCRAFT GEAR COLLAPSED ON LANDING, BROOKSVILL...",LANDING (LDG),Incident,No
7,CESSNA,Florida,210,"AIRCRAFT ON LANDING GEAR COLLAPSED, WINTER HAV...",LANDING (LDG),Incident,No
8,BOEING,Florida,747,N859GT ATLAS AIR FLIGHT GTI33 BOEING 747 AIRCR...,TAKEOFF (TOF),Incident,No
9,NaN,Florida,NaN,"AIRCRAFT, LSA PARADISE P1, ON LANDING NOSE GE...",LANDING (LDG),Incident,No
10,CESSNA,Virginia,172,AIRCRAFT ON LANDING WENT OFF THE RUNWAY INTO A...,LANDING (LDG),Incident,No
11,NaN,Arizona,FIREFLY,"N2194X FIREFLY 9 BALLOON, ON LANDING STRUCK TH...",LANDING (LDG),Incident,No
12,CESSNA,New York,310,"AIRCRAFT GEAR COLLAPSED ON LANDING, ELMIRA, NY",LANDING (LDG),Incident,No
14,BEECH,California,T34,AIRCRAFT ON TAKEOFF STRUCK RUNWAY LIGHT AT THE...,TAKEOFF (TOF),Incident,No
16,CHRISTEN,Louisiana,EAGLE II,AIRCRAFT ON TAKEOFF WENT OFF THE GRASS STRIP A...,TAKEOFF (TOF),Accident,No
17,PIPER,Missouri,PA34,"AIRCRAFT ON LANDING GEAR COLLAPSED, SPRINGFIEL...",LANDING (LDG),Incident,No
18,PIPER,Florida,PA28,"AIRCRAFT ON DEPARTURE STRUCK A BIRD, RETURNED ...",TAKEOFF (TOF),Incident,No
20,HUGHES,West Virginia,369,N1107T HUGHES 369D ROTORCRAFT MADE A PRECAUTIO...,LANDING (LDG),Incident,No
22,NaN,Arizona,NaN,"AIRCRAFT, LIGHT SPORT EVOLUTION REVO, ON TAKE...",TAKEOFF (TOF),Accident,Yes
23,BOEING,Michigan,737,AMERICAN AIRLINES FLIGHT AAL1241 BOEING 737 AI...,TAXI (TXI),Incident,No
24,GLOBE,Colorado,GC1B,"AIRCRAFT LANDED AND THE GEAR COLLAPSED, CENTEN...",LANDING (LDG),Incident,No
25,PIPER,Tennessee,PA20,"AIRCRAFT FORCE LANDED ON A HIGHWAY, NEAR DAYTO...",LANDING (LDG),Incident,No
26,GREAT LAKES,California,2T1A,"AIRCRAFT ON LANDING TIPPED ONTO ITS NOSE, PALO...",LANDING (LDG),Incident,No
28,CONSOLIDATED VULTEE,California,BT15,"AIRCRAFT ON TAXI STRUCK A PARKED AIRCRAFT, CHI...",TAXI (TXI),Incident,No
30,BEECH,Oklahoma,36,"AIRCRAFT LANDED GEAR UP, TULSA, OK",LANDING (LDG),Incident,No
32,FAIRCHILD,Texas,PT19,"AIRCRAFT ON TAXI STRUCK A PARKED AIRCRAFT, WES...",TAXI (TXI),Incident,No
33,SOCATA,Arkansas,TB9,AIRCRAFT ON TAXI WING STRUCK THE PAVEMENT AND ...,TAXI (TXI),Incident,No
34,SAAB,Florida,340,N341AG SILVER AIRWAYS FLIGHT SIL70 SAAB 340B A...,STANDING (STD),Incident,No
35,EMBRAER,Massachusetts,ERJ190,N273JB JETBLUE FLIGHT JBU891 EMBRAER ERJ190 AI...,STANDING (STD),Incident,No
36,MAULE,Alaska,M4,"AIRCRAFT ON TAKEOFF STRUCK A TAXIWAY SIGN, ANC...",TAKEOFF (TOF),Incident,No
37,ENSTROM,Michigan,NaN,"N180TH ENTROM TH180 HELICOPTER, FORCE LANDED ...",LANDING (LDG),Incident,No
38,BEECH,Florida,55,"AIRCRAFT ON TAXI, GEAR COLLAPSED, WEST PALM BE...",TAXI (TXI),Incident,No
39,MOONEY,California,M20M,"AIRCRAFT ON LANDING GEAR COLLAPSED, NAPA, CA",LANDING (LDG),Incident,No
40,PITTS,California,S2,"AIRCRAFT, N704SL CESSNA 150, AND N57BC AVIAT ...",UNKNOWN (UNK),Accident,No
44,AEROSTAR INTERNATIONAL,California,RX8,"N3647A AEROSTAR INTERNATIONAL RX8 BALLOON, ON ...",LANDING (LDG),Accident,No
46,CHAMPION,California,8KCAB,AIRCRAFT ON LANDING GROUND LOOPED AND GEAR COL...,LANDING (LDG),Accident,No
47,BELL,Nevada,47G,N1181W BELL 47G ROTORCRAFT LANDED OFF THE RUNW...,LANDING (LDG),Accident,No
48,AIRBUS,Minnesota,A319,AMERICAN AIRLINES FLIGHT AAL476 AIRBUS A319 AI...,UNKNOWN (UNK),Accident,No
49,GRUMMAN,California,AA1,"AIRCRAFT ON LANDING NOSE GEAR COLLAPSED, SALIN...",LANDING (LDG),Incident,No
50,GULFSTREAM,Virginia,GULFSTREAM200,"AIRCRAFT ON TAXI COLLIDED WITH A VEHICLE, WASH...",TAXI (TXI),Incident,No
51,SOCATA,California,TB21,"AIRCRAFT ON LANDING THE GEAR COLLAPSED, PETALU...",LANDING (LDG),Incident,No
53,PIPER,Florida,PA28,AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES. ...,UNKNOWN (UNK),Accident,Yes
55,FLIGHT DESIGN,California,CTLS,AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES A...,UNKNOWN (UNK),Accident,Yes
57,NaN,Idaho,KITFOX,"AIRCRAFT ON LANDING GEAR COLLAPSED, HELLS CANY...",LANDING (LDG),Incident,No
58,NaN,California,NaN,"AIRCRAFT, LIGHT SPORT DOVA AS SKYLARK, ON LAN...",LANDING (LDG),Incident,No
61,BEECH,California,36,AIRCRAFT FORCE LANDED IN THE WETLAND/SLOUGH AR...,LANDING (LDG),Accident,No
67,LANCAIR,Kansas,IV,"AIRCRAFT DURING FLIGHT, WINDOW SEPARATED FROM ...",UNKNOWN (UNK),Incident,No
69,MOONEY,Ohio,M20K,"AIRCRAFT ON LANDING, GEAR COLLAPSED, DEFIANCE, OH",LANDING (LDG),Incident,No
70,AERO COMMANDER,Virginia,500,"AIRCRAFT ON TAXI, GEAR RETRACTED, CHESAPEAKE, VA",TAXI (TXI),Incident,No
72,MOONEY,Maryland,M20E,AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...,LANDING (LDG),Incident,No
74,SABRELINER,Arkansas,NA265,"AIRCRAFT ON LANDING, GEAR COLLAPSED, WEST MEMP...",LANDING (LDG),Incident,No
75,MOONEY,Maryland,M20K,"AIRCRAFT ON LANDING, STRUCK A SIGN AND RUNWAY ...",LANDING (LDG),Incident,No
77,BOEING,Texas,737,SOUTHWEST AIRLINES FLIGHT SWA3817 BOEING 737 A...,NaN,Incident,No
78,AERONCA,Texas,O58B,"AIRCRAFT ON LANDING, GROUND LOOPED, BULVERDE A...",LANDING (LDG),Accident,No
79,NORTH AMERICAN,Arizona,F51,"AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES, ...",UNKNOWN (UNK),Accident,Yes
80,CHAMPION,California,8KCAB,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",UNKNOWN (UNK),Accident,Yes

In [33]:
#View the number of times each aircraft type appears in the dataset (Hint: use the size() method)

#### 7: Display the observations where fatal flag is “Yes”

In [24]:
#Group the dataset by fatal flag
df_analyze_dataset[df_analyze_dataset.FATAL_FLAG == 'Yes']

,ACFT_MAKE_NAME,LOC_STATE_NAME,ACFT_MODEL_NAME,RMK_TEXT,FLT_PHASE,EVENT_TYPE_DESC,FATAL_FLAG
0,BEECH,North Carolina,36,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",UNKNOWN (UNK),Accident,Yes
22,NaN,Arizona,NaN,"AIRCRAFT, LIGHT SPORT EVOLUTION REVO, ON TAKE...",TAKEOFF (TOF),Accident,Yes
53,PIPER,Florida,PA28,AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES. ...,UNKNOWN (UNK),Accident,Yes
55,FLIGHT DESIGN,California,CTLS,AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES A...,UNKNOWN (UNK),Accident,Yes
79,NORTH AMERICAN,Arizona,F51,"AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES, ...",UNKNOWN (UNK),Accident,Yes
80,CHAMPION,California,8KCAB,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",UNKNOWN (UNK),Accident,Yes
81,BEECH,California,35,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",UNKNOWN (UNK),Accident,Yes
82,CESSNA,Alabama,182,N784CP AIRCRAFT CRASHED INTO A WOODED AREA NEA...,UNKNOWN (UNK),Accident,Yes

In [25]:
#View the total number of fatal and non-fatal accidents
df_analyze_dataset['FATAL_FLAG'].value_counts()

No     75
Yes     8
Name: FATAL_FLAG, dtype: int64

In [26]:
#Create a new dataframe to view only the fatal accidents (Fatal Flag values = Yes)
df_new = df_analyze_dataset[df_analyze_dataset.FATAL_FLAG == 'Yes']